"""Initial schema

Revision ID: 4828bd98c15a
Revises: 
Create Date: 2026-07-07 12:27:06.132236+00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4828bd98c15a'
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('grace_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('allowed_tables', sa.JSON(), nullable=True),
    sa.Column('allowed_query_types', sa.JSON(), nullable=True),
    sa.Column('rate_limit_override', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('query_type', sa.String(length=20), nullable=True),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('slow', sa.Boolean(), nullable=False),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('query_preview', sa.String(length=500), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('execution_plan', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_anomaly_flag'), 'audit_logs', ['anomaly_flag'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_query_fingerprint'), 'audit_logs', ['query_fingerprint'], unique=False)
    op.create_index(op.f('ix_audit_logs_query_type'), 'audit_logs', ['query_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_slow'), 'audit_logs', ['slow'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('ip_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('rule_type', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_rules_ip_address'), 'ip_rules', ['ip_address'], unique=False)
    op.create_table('query_whitelist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_whitelist_query_fingerprint'), 'query_whitelist', ['query_fingerprint'], unique=True)
    op.create_table('sla_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('successful_queries', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('uptime_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slow_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('rows_scanned', sa.Integer(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('recommended_index', sa.Text(), nullable=True),
    sa.Column('execution_plan', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slow_queries_created_at'), 'slow_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_slow_queries_query_fingerprint'), 'slow_queries', ['query_fingerprint'], unique=False)
    op.create_index(op.f('ix_slow_queries_trace_id'), 'slow_queries', ['trace_id'], unique=False)
    op.create_index(op.f('ix_slow_queries_user_id'), 'slow_queries', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'readonly', 'guest', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('conn_str_enc', sa.Text(), nullable=False),
    sa.Column('encrypted_dek', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_databases_user_id'), 'user_databases', ['user_id'], unique=False)
    op.create_table('column_security',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('classification_method', sa.Integer(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['user_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'schema_name', 'table_name', 'column_name', name='uq_col_sec_conn_sch_tab_col')
    )
    op.create_index(op.f('ix_column_security_connection_id'), 'column_security', ['connection_id'], unique=False)
    op.create_table('connection_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allowed_tables', sa.Text(), nullable=True),
    sa.Column('allowed_query_types', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['user_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'user_id', name='uq_conn_perm_conn_user')
    )
    op.create_index(op.f('ix_connection_permissions_connection_id'), 'connection_permissions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_user_id'), 'connection_permissions', ['user_id'], unique=False)
    op.create_table('dek_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('encrypted_dek', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['user_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dek_history_database_id'), 'dek_history', ['database_id'], unique=False)
    op.create_table('encryption_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['user_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_audit_logs_created_at'), 'encryption_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_encryption_audit_logs_database_id'), 'encryption_audit_logs', ['database_id'], unique=False)
    op.create_table('migration_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('old_key_version', sa.Integer(), nullable=True),
    sa.Column('new_key_version', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=True),
    sa.Column('target_column', sa.String(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['user_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_jobs_database_id'), 'migration_jobs', ['database_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_jobs_database_id'), table_name='migration_jobs')
    op.drop_table('migration_jobs')
    op.drop_index(op.f('ix_encryption_audit_logs_database_id'), table_name='encryption_audit_logs')
    op.drop_index(op.f('ix_encryption_audit_logs_created_at'), table_name='encryption_audit_logs')
    op.drop_table('encryption_audit_logs')
    op.drop_index(op.f('ix_dek_history_database_id'), table_name='dek_history')
    op.drop_table('dek_history')
    op.drop_index(op.f('ix_connection_permissions_user_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_permissions_connection_id'), table_name='connection_permissions')
    op.drop_table('connection_permissions')
    op.drop_index(op.f('ix_column_security_connection_id'), table_name='column_security')
    op.drop_table('column_security')
    op.drop_index(op.f('ix_user_databases_user_id'), table_name='user_databases')
    op.drop_table('user_databases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slow_queries_user_id'), table_name='slow_queries')
    op.drop_index(op.f('ix_slow_queries_trace_id'), table_name='slow_queries')
    op.drop_index(op.f('ix_slow_queries_query_fingerprint'), table_name='slow_queries')
    op.drop_index(op.f('ix_slow_queries_created_at'), table_name='slow_queries')
    op.drop_table('slow_queries')
    op.drop_table('sla_snapshots')
    op.drop_index(op.f('ix_query_whitelist_query_fingerprint'), table_name='query_whitelist')
    op.drop_table('query_whitelist')
    op.drop_index(op.f('ix_ip_rules_ip_address'), table_name='ip_rules')
    op.drop_table('ip_rules')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_slow'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_query_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_query_fingerprint'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_anomaly_flag'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
